language: php

php:
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
  - memcached # will start memcached

before_install:
  - composer self-update

before_script:
  - composer update --dev
  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
